server:
  port: 8090

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================
application:
  name: Bus Core
  initials: BUS